### ISSUE TITLE
Is composer strictly needed?

### ISSUE THREAD

**Issue by StarkITA** [NeoIsRecursive/Emojify#1]
Hello,

very cool project! I was interested in toying with it, but the env I would be using does not have composer. Is it needed at all?

**Comment by NeoIsRecursive** [comment]
Hi!

Composer is just used for the autoload (and so you can install as a composer package), so you should be able to just include the Emojify.php file manually and use it like in the examples.

```
//include the file manually like this:
require __DIR__ . '/src/Emojify.php';

use Neoisrecursive\Emojify;

$emojify = new Emojify();

$string = 'hello here is an emoji :smile:';

$emojify->WholeString($string);
// hello, here is an emoji 😄

$emojify->IsShortname(':sunglasses:');
//bool(true)

$emojify->ShortnameToEmoji(':sunglasses:');
//string(4) "😎"
```

Let me know if there is any issues!

**Comment by StarkITA** [comment]
Thanks! I will try when I get a chance!
